import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { parseCookies } from 'nookies'
import { redirect } from 'next/navigation'
import { headers } from 'next/headers'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const headersList = headers()
  const referer = headersList.get('referer')
  const host = headersList.get('host')
  const pathname = referer?.split(host ?? '')[1] ?? '/' // 경로 추출

  const cookies = parseCookies()
  const authToken = cookies['auth-token']

  if (!authToken && pathname !== '/login') {
    redirect('/login')
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
